name: .NET Windows

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    name: Build for Windows
    runs-on: windows-latest

    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: false

      - name: Install .NET Core
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: latest
          dotnet-channel: LTS
          cache: true

      - name: Restore
        run: dotnet restore /p:Configuration=Release-win

      - name: Build
        run: dotnet build --configuration Release-win --no-restore

      - name: Publish
        run: dotnet publish '${{ runner.workspace }}/Smithbox/src/Smithbox/Smithbox.csproj' --configuration Release-win -o deploy

      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: "Smithbox-SHA${{ github.sha }}"
          path: "${{ runner.workspace }}/Smithbox/deploy"
